export const CHAMPIONS = {
  light: {
    name: 'Valorian',
    attribute: 'light',
    image: 'Valorian.webp',
    hp: 20,
    atk: 0,
    abilities: {
      attuned: {
        id: 'shield',
        name: 'Shield',
        type: 'activated',
        cost: { type: 'mana', amount: 2 },
        description: 'Give a friendly unit within 2 tiles +2 HP until end of turn.',
        targetRequired: true,
        targetFilter: 'friendly_unit_within_2',
      },
      ascended: {
        id: 'fortitude',
        name: 'Fortitude',
        type: 'passive',
        description: 'Friendly units within 2 tiles of your champion take 1 less damage during combat (minimum 1).',
      },
    },
  },
  primal: {
    name: 'Kragor',
    attribute: 'primal',
    image: 'Kragor.webp',
    hp: 20,
    atk: 0,
    abilities: {
      attuned: {
        id: 'howl',
        name: 'Howl',
        type: 'activated',
        cost: { type: 'mana', amount: 2 },
        description: 'Give a friendly unit within 2 tiles +2 ATK until end of turn.',
        targetRequired: true,
        targetFilter: 'friendly_unit_within_2',
      },
      ascended: {
        id: 'hunger',
        name: 'Hunger',
        type: 'passive',
        description: 'When a friendly unit destroys an enemy unit in combat, gain 1 temporary mana this turn.',
      },
    },
  },
  mystic: {
    name: 'Sylara',
    attribute: 'mystic',
    image: 'Sylara.webp',
    hp: 20,
    atk: 0,
    abilities: {
      attuned: {
        id: 'sapling_summon',
        name: 'Sapling Summon',
        type: 'activated',
        cost: { type: 'mana', amount: 2 },
        description: 'Summon a 1/1 Sapling in an adjacent tile.',
        targetRequired: false,
      },
      ascended: {
        id: 'nourish',
        name: 'Nourish',
        type: 'passive',
        description: 'At the beginning of your turn, your lowest HP combat unit gains +1/+1.',
      },
    },
  },
  dark: {
    name: 'Malachar',
    attribute: 'dark',
    image: 'malachar.webp',
    hp: 20,
    atk: 0,
    abilities: {
      attuned: {
        id: 'corrupt',
        name: 'Corrupt',
        type: 'activated',
        cost: { type: 'mana', amount: 2 },
        description: 'Deal 1 damage to an enemy unit.',
        targetRequired: true,
        targetFilter: 'enemy_unit',
      },
      attunedPassive: {
        id: 'soul_harvest',
        name: 'Soul Harvest',
        type: 'passive',
        description: 'The first time an enemy unit is destroyed during your turn, your champion restores 1 HP.',
      },
      ascended: {
        id: 'dark_pact',
        name: 'Dark Pact',
        type: 'activated',
        cost: { type: 'hp', amount: 2 },
        description: 'Pay 2 HP: draw a card.',
        replacesAbility: 'corrupt',
        targetRequired: false,
      },
    },
  },
};
