// Challenge pool definitions for daily and weekly challenges.
// Each challenge has a seeded-random selection so all players see the same challenges daily/weekly.

export const DAILY_CHALLENGE_POOL = [
  {
    id: 'win_with_light',
    title: 'Holy Crusade',
    description: 'Win 2 games with a Human (Light) deck.',
    type: 'daily',
    requirement: { stat: 'winsWithFaction', faction: 'light', target: 2 },
  },
  {
    id: 'win_with_primal',
    title: 'Primal Fury',
    description: 'Win 2 games with a Beast (Primal) deck.',
    type: 'daily',
    requirement: { stat: 'winsWithFaction', faction: 'primal', target: 2 },
  },
  {
    id: 'win_with_mystic',
    title: 'Ancient Wisdom',
    description: 'Win 2 games with an Elf (Mystic) deck.',
    type: 'daily',
    requirement: { stat: 'winsWithFaction', faction: 'mystic', target: 2 },
  },
  {
    id: 'win_with_dark',
    title: 'Shadow Conquest',
    description: 'Win 2 games with a Demon (Dark) deck.',
    type: 'daily',
    requirement: { stat: 'winsWithFaction', faction: 'dark', target: 2 },
  },
  {
    id: 'champion_damage_15',
    title: 'Hammer of the Gods',
    description: 'Deal 15 damage to enemy champions in a single game.',
    type: 'daily',
    requirement: { stat: 'championDamageDealt', target: 15 },
  },
  {
    id: 'units_played_10',
    title: 'Army of One',
    description: 'Play 10 units in a single game.',
    type: 'daily',
    requirement: { stat: 'unitsPlayed', target: 10 },
  },
  {
    id: 'win_under_15_turns',
    title: 'Lightning Strike',
    description: 'Win a game in under 15 turns.',
    type: 'daily',
    requirement: { stat: 'fastWin', maxTurns: 15, target: 1 },
  },
  {
    id: 'destroy_5_units',
    title: 'Warbringer',
    description: 'Destroy 5 enemy units in a single game.',
    type: 'daily',
    requirement: { stat: 'unitsDestroyed', target: 5 },
  },
  {
    id: 'cast_4_spells',
    title: 'Arcanist',
    description: 'Cast 4 spells in a single game.',
    type: 'daily',
    requirement: { stat: 'spellsCast', target: 4 },
  },
  {
    id: 'champ_no_damage',
    title: 'Untouchable',
    description: 'Win a game without your champion taking damage.',
    type: 'daily',
    requirement: { stat: 'champUndamaged', target: 1 },
  },
  {
    id: 'high_cost_cards_3',
    title: 'Heavy Hitter',
    description: 'Play 3 cards costing 5 or more in a single game.',
    type: 'daily',
    requirement: { stat: 'highCostCardsPlayed', minCost: 5, target: 3 },
  },
  {
    id: 'throne_control_3',
    title: 'King of the Hill',
    description: 'Control the Throne tile for 3 consecutive turns.',
    type: 'daily',
    requirement: { stat: 'throneControlStreak', target: 3 },
  },
  {
    id: 'win_draft',
    title: 'Draft Champion',
    description: 'Win a draft game.',
    type: 'daily',
    requirement: { stat: 'draftWin', target: 1 },
  },
  {
    id: 'champion_damage_20',
    title: 'Relentless Assault',
    description: 'Deal 20 damage to enemy champions in a single game.',
    type: 'daily',
    requirement: { stat: 'championDamageDealt', target: 20 },
  },
  {
    id: 'destroy_7_units',
    title: 'Annihilator',
    description: 'Destroy 7 enemy units in a single game.',
    type: 'daily',
    requirement: { stat: 'unitsDestroyed', target: 7 },
  },
];

export const WEEKLY_CHALLENGE_POOL = [
  {
    id: 'weekly_win_7',
    title: 'On a Roll',
    description: 'Win 7 games this week.',
    type: 'weekly',
    requirement: { stat: 'totalWins', target: 7 },
  },
  {
    id: 'weekly_win_3_factions',
    title: 'Versatile Commander',
    description: 'Win with 3 different factions this week.',
    type: 'weekly',
    requirement: { stat: 'factionWins', target: 3 },
  },
  {
    id: 'weekly_champ_damage_50',
    title: 'Champion Slayer',
    description: 'Deal 50 total champion damage across all games.',
    type: 'weekly',
    requirement: { stat: 'championDamageDealt', target: 50 },
  },
  {
    id: 'weekly_units_played_30',
    title: 'Endless Horde',
    description: 'Play 30 units across all games this week.',
    type: 'weekly',
    requirement: { stat: 'unitsPlayed', target: 30 },
  },
  {
    id: 'weekly_draft_wins_3',
    title: 'Draft Master',
    description: 'Win 3 draft games in a single run.',
    type: 'weekly',
    requirement: { stat: 'draftWins', target: 3 },
  },
  {
    id: 'weekly_win_all_factions',
    title: 'Grand Champion',
    description: 'Win a game with each of the 4 factions.',
    type: 'weekly',
    requirement: { stat: 'allFactionWins', target: 4 },
  },
  {
    id: 'weekly_destroy_20_units',
    title: 'Reaper',
    description: 'Destroy 20 enemy units across all games.',
    type: 'weekly',
    requirement: { stat: 'unitsDestroyed', target: 20 },
  },
  {
    id: 'weekly_cast_15_spells',
    title: 'Archmage',
    description: 'Cast 15 spells across all games this week.',
    type: 'weekly',
    requirement: { stat: 'spellsCast', target: 15 },
  },
];
